### ISSUE TITLE
RE1 real time graphics mod incompatible with Special K

### ISSUE THREAD

**Issue by Keith94** [masterotaku/shader-mods#2]
Hi @masterotaku! I'd like to get your shader mod and Special K working together with RE1, but they are both named `d3d9.dll` (I'm using the local installation of Special K because the global injector doesn't want to work with this game). I've tried editing the `ProxyLib = ` in `DX9Settings.ini` in an attempt to load Special K under a different name, but I can't get it working. Any ideas to fix this issue?

**Comment by masterotaku** [comment]
Do the opposite, like in my two "Tales of" WIP fixes. Rename the Helixmod "d3d9.dll" to something else, like "visiond3d9.dll", and then put this in the SpecialK "d3d9.ini":

[Import.visiond3d9]
Architecture=Win32
Filename=visiond3d9.dll
When=Late
Role=d3d9

Then obviously use the SpecialK "d3d9.dll" as is. And don't use ReShade, unless it miraculously works.

**Comment by Keith94** [comment]
Sweet, it worked! Thanks for the fix man.

Not sure if you do requests, but it'd be nice if you can add "remove black bars in cutscenes" for RE1 or RE0 sometime if you get the chance.

**Comment by masterotaku** [comment]
I think I'll do that :). It's something I started doing with Trails of Cold Steel, long after the RE0 and RE1 mods. And it's something that I now want for myself, now that you mention it.

I have the games installed so I'll try it soon. It will work if it's just a shader imposed over the image, unlike in Resident Evil 5.

**Comment by Keith94** [comment]
Glad to hear that. 👍
I've opened a new issue for it just in case: #3
